USE [master]
GO
/****** Object:  Database [DBAUtility]    Script Date: 9/5/2017 7:17:57 AM ******/
CREATE DATABASE [DBAUtility]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBAUtility', FILENAME = N'F:\Data\DBAUtility.mdf' , SIZE = 196608KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBAUtility_log', FILENAME = N'F:\Log\DBAUtility_log.ldf' , SIZE = 327680KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DBAUtility] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBAUtility].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [DBAUtility] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBAUtility] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBAUtility] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBAUtility] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBAUtility] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBAUtility] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBAUtility] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBAUtility] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBAUtility] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBAUtility] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBAUtility] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBAUtility] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBAUtility] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBAUtility] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBAUtility] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBAUtility] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBAUtility] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBAUtility] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBAUtility] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBAUtility] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBAUtility] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBAUtility] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBAUtility] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBAUtility] SET  MULTI_USER 
GO
ALTER DATABASE [DBAUtility] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBAUtility] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBAUtility] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBAUtility] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DBAUtility] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DBAUtility', N'ON'
GO
ALTER DATABASE [DBAUtility] SET QUERY_STORE = OFF
GO
USE [DBAUtility]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [DBAUtility]
GO
/****** Object:  User [biteam]    Script Date: 9/5/2017 7:17:57 AM ******/
CREATE USER [biteam] FOR LOGIN [biteam] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[test]    Script Date: 9/5/2017 7:17:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[test](
	[col1] [int] NULL
) ON [PRIMARY]

GO
EXEC [DBAUtility].sys.sp_addextendedproperty @name=N'SQLSourceControl Scripts Location', @value=N'<?xml version="1.0" encoding="utf-16" standalone="yes"?>
<ISOCCompareLocation version="1" type="SvnLocation">
  <RepositoryUrl>http://svn.atl.primedia.com/repos/dev-project/trunk/BusinessIntelligence/Warehouse01/Databases/DBAUtility/</RepositoryUrl>
</ISOCCompareLocation>' 
GO
EXEC [DBAUtility].sys.sp_addextendedproperty @name=N'SQLSourceControl Database Revision', @value=76485 
GO
USE [master]
GO
ALTER DATABASE [DBAUtility] SET  READ_WRITE 
GO
